const BOOKING_CENTER_HK = "HK";
const BOOKING_CENTER_SG = "SG";

const INVESTMENT_OBJECTIVE_CAPITAL_PRESERVE = "Capital Preservation";
const INVESTMENT_OBJECTIVE_INCOME = "Income";
const INVESTMENT_OBJECTIVE_INCOME_GROWTH = "Income And Growth";
const INVESTMENT_OBJECTIVE_GROWTH = "Growth";
const INVESTMENT_OBJECTIVE_SPECULATION_TRADING = "Speculation/Trading";

const RISK_TOLERANCE_CONSERVATIVE = "Conservative"
const RISK_TOLERANCE_MODERATE = "Moderate"
const RISK_TOLERANCE_AGGRESIVE = "Aggeresive"
const RISK_TOLERANCE_VERY_AGGRESIVE = "Very Aggresive"


